[theme]
primaryColor = "#E50914"
backgroundColor = "#0A0A0A"
secondaryBackgroundColor = "#181818"
textColor = "#F5F5F5"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false